name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # Replace with your desired PHP version

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: vendor/bin/phpunit # Replace with your test command

      # You can add more steps here, like deploying, code analysis, etc.
